name: Rust

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --features remote --verbose
      - name: Run tests
        run: cargo test --features remote --verbose
      - name: Run benches
        run: cargo bench --features remote --verbose
